version: '3.0'
services:
  back:
    image: node
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: sh start.sh
    networks:
      - default

  neo4j:
    image: neo4j
    volumes:
      - ./neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    networks:
      - default

  front:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - back
    working_dir: /usr/src/app
    entrypoint: sh start.sh
    networks:
      - default

networks:
  default:
    driver: bridge